name: SAP_Raid

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Prepare Addon Folder
        run: |
          mkdir -p package/SAP_Raid
          shopt -s extglob
          cp -r !(package|.git|.github) package/SAP_Raid/

      - name: Create ZIP with tag suffix
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          cd package
          zip -r SAP_Raid-v${TAG_NAME}.zip SAP_Raid/
          echo "ZIP_NAME=SAP_Raid-v${TAG_NAME}.zip" >> $GITHUB_ENV

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: package/${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
